package com.swp391.clubmanagement.enums;

public enum ClubCategory {
    HocThuat,    // IT, English, Science...
    TheThao,     // Soccer, Badminton...
    NgheThuat,   // Music, Dance, Art...
    TinhNguyen,  // Volunteer, Social work...
    Khac         // Other
}

